### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by kyeming** [hemnathmouli/WC-Wallet#1]
Could you tell me how to display a single user wc wallet balance and history log?

**Comment by kyeming** [comment]
Sorry, I'm not very clear point out my situation/issues, let me try to describe again. Total two issues as below:

issue#1: when my customer cancel the order, the money donesn't back to their WC wallet, please tell me how to resolve this problem.

issue#2 :my customer can't see or review their balance on their side instead of my side, so my customer always need my assistant to check their balance, please tell me how to resolve this problem.

**Comment by hemnathmouli** [comment]
Hi @kyeming 
issue#1: I have updated the bug. Please update.
issue#2: you can use the shortcode `[wc_wallet_show_balance]` to show user, their balance in their balance.

And the FILTER, is set with the new update.!

**Comment by kyeming** [comment]
Thank you for your answer ^^
Question 1 with 2 has been resolved, but I found a new problem -
Guests buy goods if he chose atm payment, when I set atm payment order is canceled, the points can be stored into  wc wallet, but when the guests cancel the order with did not pay down the order , they also can get the integration, Please kindly help me solve this problem again. Thank you...

In addition, the ability to recommend an increase in the plug several limitations, such as: How many full commodity price required in order to use wc purse deductions (shipping not included), can not be used to exclude specific Category wc purse deductions, so that the entire plug-in is even more perfect ^^any help would be appreciate...

**Comment by hemnathmouli** [comment]
Hello. I have made some update. Please check setting page, hope it would help you.!
